Repository STeres-work/BotAlert, pull requests merged in 2021-08, with the labels that each got.

#11 Added create feature
  .gitignore
  BotAlert.Tests/BotAlert.Tests.csproj
  BotAlert.Tests/EventProviderTests.cs
  BotAlert.Tests/InputDateStateTests.cs
  BotAlert.Tests/InputDescriptionKeyboardStateTests.cs
  BotAlert.Tests/InputDescriptionStateTests.cs
  BotAlert.Tests/InputTitleStateTests.cs
  BotAlert.Tests/InputWarnDateKeyboardStateTests.cs
  BotAlert.Tests/InputWarnDateStateTests.cs
  BotAlert.Tests/InteractionHelperTests.cs
  BotAlert.Tests/MainStateTests.cs
  BotAlert.Tests/SaveStateTests.cs
  BotAlert.Tests/StateFactoryTests.cs
  BotAlert.Tests/StateProviderTests.cs
  BotAlert.Tests/TelegramUpdatesHandlerTests.cs
  BotAlert/BotAlert.csproj
  BotAlert/Controllers/TelegramUpdatesHandler.cs
  BotAlert/Factories/StateFactory.cs
  BotAlert/Helpers/InteractionHelper.cs
  BotAlert/Interfaces/IEventProvider.cs
  BotAlert/Interfaces/IState.cs
  BotAlert/Interfaces/IStateFactory.cs
  BotAlert/Interfaces/IStateProvider.cs
  BotAlert/Interfaces/ITelegramUpdatesHandler.cs
  BotAlert/Models/ChatState.cs
  BotAlert/Models/ContextState.cs
  BotAlert/Models/Event.cs
  BotAlert/Models/EventStatus.cs
  BotAlert/Program.cs
  BotAlert/Services/EventProvider.cs
  BotAlert/Services/StateProvider.cs
  BotAlert/Settings/DBSettings.cs
  BotAlert/Settings/TelegramSettings.cs
  BotAlert/Startup.cs
  BotAlert/States/InputDateState.cs
  BotAlert/States/InputDescriptionKeyboardState.cs
  BotAlert/States/InputDescriptionState.cs
  BotAlert/States/InputTitleState.cs
  BotAlert/States/InputWarnDateKeyboard.cs
  BotAlert/States/InputWarnDateState.cs
  BotAlert/States/MainState.cs
  BotAlert/States/SaveState.cs
  BotAlert/TelegramBotExtensions.cs
  BotAlert/appsettings.Development.json
  BotAlert/appsettings.json
Labels: Core functionality

#12 Fixed user prompt message
  BotAlert/States/InputWarnDateKeyboard.cs
Labels: bug

#16 Added receive notification feature
  BotAlert.Tests/EventProviderTests.cs
  BotAlert.Tests/NotificationSenderServiceTests.cs
  BotAlert/BotAlert.csproj
  BotAlert/Interfaces/IEventProvider.cs
  BotAlert/Services/EventProvider.cs
  BotAlert/Services/NotificationSenderService.cs
  BotAlert/Startup.cs
  BotAlert/TelegramBotExtensions.cs
Labels: Core functionality

#18 Bugfix refactor
  BotAlert.Tests/EventProviderTests.cs
  BotAlert.Tests/GetAllNotificationsStateTests.cs
  BotAlert.Tests/InputDateStateTests.cs
  BotAlert.Tests/InputDescriptionStateTests.cs
  BotAlert.Tests/InputTitleStateTests.cs
  BotAlert.Tests/InputWarnDateKeyboardStateTests.cs
  BotAlert.Tests/InputWarnDateStateTests.cs
  BotAlert.Tests/MainStateTests.cs
  BotAlert.Tests/NotificationSenderServiceTests.cs
  BotAlert.Tests/SaveStateTests.cs
  BotAlert.Tests/StateFactoryTests.cs
  BotAlert.Tests/StateProviderTests.cs
  BotAlert.Tests/TelegramUpdatesHandlerTests.cs
  BotAlert/BotAlert.csproj
  BotAlert/Handlers/TelegramUpdatesHandler.cs
  BotAlert/Helpers/DateTimeExtensions.cs
  BotAlert/Interfaces/IEventProvider.cs
  BotAlert/Models/Event.cs
  BotAlert/Program.cs
  BotAlert/Services/EventProvider.cs
  BotAlert/Services/NotificationSenderService.cs
  BotAlert/Services/StateProvider.cs
  BotAlert/Startup.cs
  BotAlert/States/EditState.cs
  BotAlert/States/GetAllNotificationsState.cs
  BotAlert/States/GetNotificationDetailsState.cs
  BotAlert/States/InputDateState.cs
  BotAlert/States/InputDeleteKeyboardState.cs
  BotAlert/States/InputDescriptionKeyboardState.cs
  BotAlert/States/InputDescriptionState.cs
  BotAlert/States/InputTitleState.cs
  BotAlert/States/InputWarnDateKeyboardState.cs
  BotAlert/States/InputWarnDateState.cs
  BotAlert/States/MainState.cs
  BotAlert/States/SaveState.cs
  BotAlert/appsettings.Development.json
Labels: Refactoring

#22 Feature deployment
  .github/workflows/BotAlert.yml
Labels: Core functionality
